---
lessonName: Automating the Troubleshooting Chain
lessonID: 21
category: troubleshooting
lessondiagram: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-21/lessondiagram.png
topologyType: custom
# disabled: true

blackboxes:
- name: asterisk
  image: antidotelabs/asterisk
  ports: [8088]
- name: netbox
  image: antidotelabs/netbox
  ports: [8000]

devices:
- name: vqfx1
  image: antidotelabs/vqfxspeedy:snap1
  sshuser: root
  sshpassword: VR-netlab9
- name: vqfx2
  image: antidotelabs/vqfxspeedy:snap2
  sshuser: root
  sshpassword: VR-netlab9
- name: vqfx3
  image: antidotelabs/vqfxspeedy:snap3
  sshuser: root
  sshpassword: VR-netlab9
  
utilities:
- name: linux1
  image: antidotelabs/utility
  sshuser: antidote
  sshpassword: antidotepassword
- name: sipphone
  image: antidotelabs/pjsua-lindsey
  sshuser: antidote
  sshpassword: antidotepassword
  ports: [22]

connections:
- a: vqfx1
  b: vqfx2
  subnet: 10.10.10.0/24
- a: vqfx2
  b: vqfx3
  subnet: 10.10.20.0/24
- a: vqfx3
  b: vqfx1
  subnet: 10.10.30.0/24
- a: vqfx2
  b: sipphone
  subnet: 10.10.150.0/24
- a: vqfx1
  b: netbox
  subnet: 10.10.100.0/24
- a: vqfx1
  b: asterisk
  subnet: 10.10.200.0/24


stages:
  1:
    description: Get the IP Address for a Phone Extension
    labguide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-21/stage1/guide.md
    configs:
      vqfx1: stage1/configs/vqfx1.txt
      vqfx2: stage1/configs/vqfx2.txt
      vqfx3: stage1/configs/vqfx3.txt
