---
lessonName: Multi-Vendor Network Automation with NAPALM
lessonID: 13
category: configuration
topologyType: custom


utilities:
- name: linux1
  image: antidotelabs/utility
  sshuser: antidote
  sshpassword: antidotepassword

devices:
- name: vqfx1
  image: antidotelabs/vqfxspeedy:snap1
  sshuser: root
  sshpassword: VR-netlab9
- name: vqfx2
  image: antidotelabs/vqfxspeedy:snap2
  sshuser: root
  sshpassword: VR-netlab9
- name: vqfx3
  image: antidotelabs/vqfxspeedy:snap3
  sshuser: root
  sshpassword: VR-netlab9

connections:
- a: vqfx1
  b: vqfx2
  subnet: 10.12.0.0/24
- a: vqfx2
  b: vqfx3
  subnet: 10.23.0.0/24
- a: vqfx3
  b: vqfx1
  subnet: 10.31.0.0/24
- a: vqfx1
  b: linux1
  subnet: 10.1.0.0/24

stages:
  1:

    description: Get device facts
    labguide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-13/stage1/guide.md

    configs:
      vqfx1: stage1/configs/vqfx1.txt
      vqfx2: stage1/configs/vqfx2.txt
      vqfx3: stage1/configs/vqfx3.txt

    iframeresource:
      name: jupyter
      protocol: https
      uri: "/notebooks/lesson-13/stage1/notebook.ipynb"
      port: 8888
