---
hosts:
  - device: vqfx1
    username : root
    passwd: VR-netlab9
    port: 22
  - device: vqfx2
    username : root
    passwd: VR-netlab9
    port: 22
  - device: vqfx3
    username : root
    passwd: VR-netlab9
    port: 22
tests:
    - jsnapy_tests.yaml
